# Generated by Django 5.1.4 on 2025-01-26 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='body',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
