# Generated by Django 5.1.4 on 2025-01-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_body_delete_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
