# Generated by Django 5.1.4 on 2025-02-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author'),
        ('products', '0007_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='related_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='blog.post'),
        ),
    ]
