# Generated by Django 5.1.4 on 2025-02-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_related_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lazada_affiliate_link',
            field=models.URLField(blank=True, help_text='Affiliate link for Lazada', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shopee_affiliate_link',
            field=models.URLField(blank=True, help_text='Affiliate link for Shopee', null=True),
        ),
    ]
